[[redirects]]
  from = "/team"
  to = "/"
  status = 200
  force = true

[[redirects]]
  from = "/supportus"
  to = "/"
  status = 200
  force = true

[[redirects]]
  from = "/projects"
  to = "/"
  status = 200
  force = true